version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-lein
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "project.clj" }}
      - run:
          command: |
            bash generate.sh
      - save_cache:
          paths:
            - ~/.m2
          key: v2-dependencies-{{ checksum "project.clj" }}
      - persist_to_workspace:
          root: target
          paths: out

  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Install and deploy target files to netlify
          command: |
            npm install -g --silent netlify-cli
            netlify deploy --auth=${NETLIFY_PERSONAL_ACCESS_TOKEN} --site=${NETLIFY_SITE_ID} --dir=target/out --prod

workflows:
  version: 2
  deploy_to_netlify:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy:
          requires:
            - build
